//literal[]
let d = [2,8,7,9];
console.log(a);
let p = new Array(2,4,7,8);
console.log(p);


// Using Map
let a = [2,8,7];
let b = new Array(2,4,7);
//call back funtion waits for the other function
let c = b.map(item => item*2)
console.log(b);
console.log(c);

let fruits = ["Apples","Mango","Banana"]
let newfruits = fruits.map(item => item.toLocaleLowerCase())
console.log(newfruits)

//condition
let fruit = ["Apples","Mango","Banana"]
let newfruit = fruits.map(item =>)
    if

let oddNumbers = b.filter(item => item%2 !==0)
console.log({oddNumbers});

let e = [2,8,7];
a[1] = 20
console.log(e[1]);